# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnStreetParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('isOccupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('parked_users', models.PositiveIntegerField(default=0)),
                ('isFull', models.BooleanField(default=False)),
                ('price_per_hour', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOccupied', models.BooleanField(default=False)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.ParkingLot')),
            ],
        ),
    ]
