# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20180527_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='parked_user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
