# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20180527_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='parked_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='price_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='isFull',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
