# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_parkinglot_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='moderator',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
