# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dustbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.TextField()),
                ('latitude', models.TextField()),
                ('location', models.TextField()),
                ('isFull', models.BooleanField()),
            ],
        ),
    ]
